name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Linux x86_64
          - os: ubuntu-latest
            platform: linux-x86_64
            cc: gcc
          
          # macOS x86_64 
          - os: macos-latest
            platform: macos-x86_64
            cc: clang
          
          # macOS ARM64
          - os: macos-14
            platform: macos-arm64
            cc: clang

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build static binaries
      run: |
        CC=${{ matrix.cc }} make static
        strip cpdd syndir || true

    - name: Test binaries
      run: |
        ./cpdd --help
        ./syndir --help
        # Run test with fewer files for CI speed
        ./test_cpdd.sh -f 50

    - name: Create release archive
      run: |
        VERSION="${GITHUB_REF#refs/tags/}"
        ARCHIVE_NAME="cpdd-${VERSION#v}-${{ matrix.platform }}"
        
        mkdir -p dist/$ARCHIVE_NAME
        
        # Copy binaries
        cp cpdd syndir dist/$ARCHIVE_NAME/
        
        # Copy documentation  
        cp README.md dist/$ARCHIVE_NAME/ || true
        cp -r man dist/$ARCHIVE_NAME/ || true
        
        # Create archive
        cd dist
        tar -czf ${ARCHIVE_NAME}.tar.gz $ARCHIVE_NAME
        
        # Calculate checksums
        if command -v sha256sum >/dev/null; then
          sha256sum ${ARCHIVE_NAME}.tar.gz > ${ARCHIVE_NAME}.tar.gz.sha256
        else
          shasum -a 256 ${ARCHIVE_NAME}.tar.gz > ${ARCHIVE_NAME}.tar.gz.sha256
        fi

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cpdd-${{ matrix.platform }}
        path: |
          dist/*.tar.gz
          dist/*.sha256

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create release notes
      run: |
        VERSION="${GITHUB_REF#refs/tags/}"
        cat > release_notes.md << EOF
        # cpdd ${VERSION}
        
        Content-based copy with deduplication - Binary releases for multiple platforms.
        
        ## Downloads
        
        Choose the appropriate binary for your platform:
        
        - **Linux x86_64**: \`cpdd-*-linux-x86_64.tar.gz\`
        - **macOS x86_64**: \`cpdd-*-macos-x86_64.tar.gz\`
        - **macOS ARM64**: \`cpdd-*-macos-arm64.tar.gz\`
        
        ## Installation
        
        1. Download the appropriate archive for your platform
        2. Extract: \`tar -xzf cpdd-*.tar.gz\`
        3. Copy binaries to your PATH: \`sudo cp cpdd-*/cpdd cpdd-*/syndir /usr/local/bin/\`
        4. Install man pages: \`sudo cp cpdd-*/man/*.1 /usr/local/share/man/man1/\`
        
        ## Verification
        
        Each archive includes a SHA256 checksum file. Verify with:
        \`\`\`bash
        sha256sum -c cpdd-*.tar.gz.sha256
        \`\`\`
        
        See the commit history for changes in this release.
        EOF

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: cpdd ${{ github.ref_name }}
        body_path: release_notes.md
        draft: false
        prerelease: false
        files: |
          artifacts/**/*.tar.gz
          artifacts/**/*.sha256
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}